# Generated by Django 2.2.11 on 2020-03-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0097_participation_is_disqualified'),
    ]

    operations = [
    ]
