# Generated by Django 2.2.12 on 2020-05-03 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0104_contestproblem_maxsubs'),
    ]

    operations = [
    ]
